language: node_js
node_js: node
install:
  - npm install
script:
  - npm run build
  - npm run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist
  on:
    branch: master
